### ISSUE TITLE
Invalid reference to FROM-clause entry

### ISSUE THREAD

**Issue by brandondong** [alex-w0/objection-js-soft-delete#108]
For the query:
```javascript
return await Organization.query().whereExists(
  Organization.relatedQuery('memberships').where('userId', 1)
);
```
And with the Organization relations defined as:
```javascript
memberships: {
  relation: Model.HasManyRelation,
  modelClass: Membership,
  join: {
    from: 'organization.id',
    to: 'membership.organizationId'
  },
  filter: o => o.whereNotDeleted()
}
```
(Note the relation name is intentionally different than the table name because we want joined/fetched entries to be named this way)

Generates the following error:
```sql
select "organization".* from "organization" where exists (select "memberships".* from "membership" as "memberships" where "memberships"."organization_id" = "organization"."id" and "membership"."deleted_on" = $1 and "user_id" = $2) - invalid reference to FROM-clause entry for table "membership"
```

Objection.js is renaming the table in the query and I believe https://github.com/alex-w0/objection-js-soft-delete/blob/30da77e19c77294b072e96fdee21e89f8a8fb2a6/src/softDelete.js#L56 is reliant on this never happening.

**Comment by alex-w0** [comment]
Hi, I think the issue here is that the relatedQuery is using for the query the given alias name 'memberships' (which is totally legit) and the plugin is extending the query with the original table name 'membership'. This inconsistency leads to the invalid sql query.

```
`from "membership" as "memberships" where "memberships"."organization_id" = "organization"."id" and "membership"."deleted_on" = $1
```

After some research I found only a workaround to alias the relationship back to the original name:
```
return await Organization.query().whereExists(
  Organization.relatedQuery('memberships').as('membership').where('userId', 1)
);
```
Besides that I could not find a cleaner solution for it to extract the current alias table name in the plugin. Do you have a better solution, so that the plugin can handle this use case?

**Comment by brandondong** [comment]
I had already renamed the relation mapping to be consistent with the table name and just adapted the application code to compensate. I filed the bug because I thought maybe there was some solution in the plugin itself so that whereNotDeleted() could work in all query contexts. Feel free to close if not the case.

**Comment by alex-w0** [comment]
Unfortunately I could not find a way how I can access the query context from the model context. If you find a way how this can be done, then let me know, because I'm curious too. It would be really useful if the plugin can handle this by itself.

I let the ticket open with the label 'help wanted'. Maybe someone has an idea.

**Comment by zsf3** [comment]
@alex-w0 I am also facing same problem. I fixed it using following:

```javascript
const tableRef = this.tableRefFor(this.modelClass());

return this.where(
    `${tableRef}.${options.columnName}`,
    options.notDeletedValue
);
```

The query context has this function of `tableRefFor`. Here is the documentation: https://vincit.github.io/objection.js/api/query-builder/other-methods.html#tablereffor

**Comment by alex-w0** [comment]
@zsf3 Thanks that should solve the problem. I've already merged the changes.
